# Generated by Django 4.1 on 2023-12-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vehiclehistory',
            name='inspection_date',
        ),
        migrations.RemoveField(
            model_name='vehiclehistory',
            name='inspection_description',
        ),
    ]
