# Generated by Django 4.1 on 2023-12-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_owner_birth_date_remove_owner_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Benzyna'), ('hybrid', 'Gaz+Benzyna')], max_length=10),
        ),
    ]
